"use client";

import UserCRUD from "../../_components/UserCrud";
import { useState } from "react";

export default function UserManagementPage() {
  // Sample user data
  const [users, setUsers] = useState([]);

  return (
    <div value="user-management" className="space-y-6">
      <UserCRUD setUsers={setUsers} users={users} />
    </div>
  );
}

const sampleUsers = [
  {
    id: 1,
    role: "principal",
    status: "active",
    lastLogin: "2024-01-15",
    name: "Dr. John Smith",
    email: "john.smith@school.edu",
    phone: "+91-9876543210",
    qualification: "PhD in Education",
    experience_years: 15,
    joining_date: "2020-01-15",
    address: "123 School Street, City",
    emergency_contact: "+91-9876543211",
  },
  {
    id: 2,
    role: "hod",
    status: "active",
    lastLogin: "2024-01-14",
    name: "Dr. Sarah Johnson",
    email: "sarah.j@school.edu",
    phone: "+91-9876543220",
    department: "Mathematics",
    qualification: "PhD in Mathematics",
    specialization: "Applied Mathematics",
    experience_years: 12,
    joining_date: "2021-06-01",
    employee_id: "EMP001",
  },
  {
    id: 3,
    role: "transport_incharge",
    status: "active",
    lastLogin: "2024-01-13",
    name: "Ms. Emily Davis",
    email: "emily.d@school.edu",
    phone: "+91-9876543230",
    qualification: "Masters in Library Science",
    library_science_degree: "MLIS",
    experience_years: 8,
    joining_date: "2022-03-15",
    employee_id: "LIB001",
    shift_timing: "Morning",
  },
  {
    id: 4,
    role: "librarian",
    status: "active",
    lastLogin: "2024-01-13",
    name: "Ms. Emily Davis",
    email: "emily.d@school.edu",
    phone: "+91-9876543230",
    qualification: "Masters in Library Science",
    library_science_degree: "MLIS",
    experience_years: 8,
    joining_date: "2022-03-15",
    employee_id: "LIB001",
    shift_timing: "Morning",
  },
  {
    id: 5,
    role: "admin",
    status: "active",
    lastLogin: "2024-01-13",
    name: "Ms. Emily Davis",
    email: "emily.d@school.edu",
    phone: "+91-9876543230",
    qualification: "Masters in Library Science",
    library_science_degree: "MLIS",
    experience_years: 8,
    joining_date: "2022-03-15",
    employee_id: "LIB001",
    shift_timing: "Morning",
  },
  {
    id: 6,
    role: "faculty",
    status: "active",
    lastLogin: "2024-01-13",
    name: "Ms. Emily Davis",
    email: "emily.d@school.edu",
    phone: "+91-9876543230",
    qualification: "Masters in Library Science",
    library_science_degree: "MLIS",
    experience_years: 8,
    joining_date: "2022-03-15",
    employee_id: "LIB001",
    shift_timing: "Morning",
  },
  {
    id: 7,
    role: "librarian",
    status: "active",
    lastLogin: "2024-01-13",
    name: "Ms. Emily Davis",
    email: "emily.d@school.edu",
    phone: "+91-9876543230",
    qualification: "Masters in Library Science",
    library_science_degree: "MLIS",
    experience_years: 8,
    joining_date: "2022-03-15",
    employee_id: "LIB001",
    shift_timing: "Morning",
  },
  {
    id: 8,
    role: "parent",
    status: "inactive",
    lastLogin: "2024-01-13",
    name: "Ms. Emily Davis",
    email: "emily.d@school.edu",
    phone: "+91-9876543230",
    qualification: "Masters in Library Science",
    library_science_degree: "MLIS",
    experience_years: 8,
    joining_date: "2022-03-15",
    employee_id: "LIB001",
    shift_timing: "Morning",
  },
  {
    id: 9,
    role: "librarian",
    status: "active",
    lastLogin: "2024-01-13",
    name: "Ms. Emily Davis",
    email: "emily.d@school.edu",
    phone: "+91-9876543230",
    qualification: "Masters in Library Science",
    library_science_degree: "MLIS",
    experience_years: 8,
    joining_date: "2022-03-15",
    employee_id: "LIB001",
    shift_timing: "Morning",
  },
];
