const userRoles = [
  "super_admin",
  "admin",
  "principal",
  "vice_principal",
  "hod",
  "parent",
  "librarian",
  "accountant",
  "hr_manager",
  "receptionist",
  "counselor",
  "lab_assistant",
  "transport_incharge",
  "driver",
  "security_guard",
  "maintenance_staff",
  "vendor",
  "guest",
];

// Convert to array of objects with label and value
const roleOptions = userRoles.map((role) => ({
  value: role,
  label: role
    .split("_")
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
    .join(" "),
}));

// Function to get assignable roles
export const getAssignableRoles = (assignerRole) => {
  const roleHierarchy = {
    super_admin: 10,
    admin: 9,
    principal: 8,
    vice_principal: 7,
    hod: 6,
    teacher: 5,
    faculty: 5,
    librarian: 4,
    accountant: 4,
    hr_manager: 4,
    counselor: 4,
    lab_assistant: 3,
    transport_incharge: 3,
    driver: 3,
    security_guard: 3,
    maintenance_staff: 3,
    receptionist: 2,
    student: 1,
    parent: 1,
    vendor: 1,
    guest: 0,
  };

  if (!roleHierarchy[assignerRole]) return [];

  const assignerLevel = roleHierarchy[assignerRole];

  return roleOptions.filter((role) => {
    const targetLevel = roleHierarchy[role.value];
    return assignerLevel > targetLevel;
  });
};

// Define user role configurations with specific fields
export const userRoleConfigs = {
  super_admin: {
    title: "Super Admin",
    color: "bg-red-50 border-red-200 text-red-800",
    fields: [
      "fullName",
      "username",
      "email",
      "phone",
      "emergency_contact",
      "access_level",
      "department",
    ],
  },
  admin: {
    title: "Admin",
    color: "bg-red-50 border-red-200 text-red-800",
    fields: [
      "fullName",
      "username",
      "email",
      "phone",
      "department",
      "access_level",
      "reports_to",
    ],
  },
  principal: {
    title: "Principal",
    color: "bg-purple-50 border-purple-200 text-purple-800",
    fields: [
      "fullName",
      "username",
      "email",
      "phone",
      "qualification",
      "experience_years",
      "joining_date",
      "address",
      "emergency_contact",
    ],
  },
  vice_principal: {
    title: "Vice Principal",
    color: "bg-purple-50 border-purple-200 text-purple-800",
    fields: [
      "fullName",
      "username",
      "email",
      "phone",
      "qualification",
      "experience_years",
      "specialization",
      "joining_date",
      "reports_to",
    ],
  },
  hod: {
    title: "Head of Department",
    color: "bg-blue-50 border-blue-200 text-blue-800",
    fields: [
      "fullName",
      "username",
      "email",
      "phone",
      "department",
      "qualification",
      "specialization",
      "experience_years",
      "joining_date",
      "employee_id",
    ],
  },
  faculty: {
    title: "Faculty",
    color: "bg-green-50 border-green-200 text-green-800",
    fields: [
      "fullName",
      "username",
      "email",
      "phone",
      "qualification",
      "specialization",
      "experience_years",
      "joining_date",
      "employee_id",
      "department",
      "access_level",
    ],
  },
  counselor: {
    title: "Counselor",
    color: "bg-green-50 border-green-200 text-green-800",
    fields: [
      "fullName",
      "username",
      "email",
      "phone",
      "qualification",
      "specialization",
      "license_number",
      "experience_years",
      "joining_date",
      "consultation_hours",
    ],
  },
  librarian: {
    title: "Librarian",
    color: "bg-indigo-50 border-indigo-200 text-indigo-800",
    fields: [
      "fullName",
      "username",
      "email",
      "phone",
      "qualification",
      "library_science_degree",
      "experience_years",
      "joining_date",
      "employee_id",
      "shift_timing",
    ],
  },
  accountant: {
    title: "Accountant",
    color: "bg-yellow-50 border-yellow-200 text-yellow-800",
    fields: [
      "fullName",
      "username",
      "email",
      "phone",
      "qualification",
      "certification",
      "experience_years",
      "joining_date",
      "employee_id",
      "department",
    ],
  },
  hr_manager: {
    title: "HR Manager",
    color: "bg-pink-50 border-pink-200 text-pink-800",
    fields: [
      "fullName",
      "username",
      "email",
      "phone",
      "qualification",
      "hr_certification",
      "experience_years",
      "joining_date",
      "employee_id",
      "department",
    ],
  },
  receptionist: {
    title: "Receptionist",
    color: "bg-cyan-50 border-cyan-200 text-cyan-800",
    fields: [
      "fullName",
      "username",
      "email",
      "phone",
      "qualification",
      "languages_known",
      "joining_date",
      "employee_id",
      "shift_timing",
    ],
  },
  lab_assistant: {
    title: "Lab Assistant",
    color: "bg-orange-50 border-orange-200 text-orange-800",
    fields: [
      "fullName",
      "username",
      "email",
      "phone",
      "qualification",
      "lab_specialization",
      "experience_years",
      "joining_date",
      "employee_id",
      "lab_assigned",
    ],
  },
  transport_incharge: {
    title: "Transport In-charge",
    color: "bg-emerald-50 border-emerald-200 text-emerald-800",
    fields: [
      "fullName",
      "username",
      "email",
      "phone",
      "driving_license",
      "license_expiry",
      "experience_years",
      "joining_date",
      "employee_id",
      "routes_managed",
    ],
  },
  vendor: {
    title: "Vendor",
    color: "bg-slate-50 border-slate-200 text-slate-800",
    fields: [
      "fullName",
      "username",
      "email",
      "phone",
      "company_name",
      "gst_number",
      "services_provided",
      "contract_start",
      "contract_end",
      "address",
    ],
  },
  security_guard: {
    title: "Security Guard",
    color: "bg-slate-50 border-slate-200 text-slate-800",
    fields: ["fullName", "username", "email", "phone", "address"],
  },
  driver: {
    title: "Driver",
    color: "bg-slate-50 border-slate-200 text-slate-800",
    fields: ["fullName", "username", "email", "phone", "address"],
  },
  maintenance_staff: {
    title: "Maintenance Staff",
    color: "bg-slate-50 border-slate-200 text-slate-800",
    fields: ["fullName", "username", "email", "phone", "address"],
  },
  guest: {
    title: "Guest",
    color: "bg-gray-50 border-gray-200 text-gray-800",
    fields: [
      "fullName",
      "username",
      "email",
      "phone",
      "purpose_of_visit",
      "visiting_department",
      "visit_date",
      "id_proof_type",
      "id_proof_number",
    ],
  },
  parent: {
    title: "Parent",
    color: "bg-teal-50 border-teal-200 text-teal-800",
    fields: [
      "fullName",
      "username",
      "email",
      "phone",
      "occupation",
      "student_name",
      "student_class",
      "relationship",
      "address",
      "emergency_contact",
    ],
  },
};

// Field configurations for form rendering
export const fieldConfigs = {
  fullName: { label: " Full Name", type: "text" },
  username: { label: "Username", type: "text", required: true },
  email: { label: "Email Address", type: "email", required: true },
  phone: { label: "Phone Number", type: "tel", required: true },
  emergency_contact: {
    label: "Emergency Contact",
    type: "tel",
    required: false,
  },
  access_level: {
    label: "Access Level",
    type: "select",
    options: ["Full", "Limited", "Read Only"],
    required: false,
  },
  department: {
    label: "Department",
    type: "select",
    options: ["Administration", "Academic", "Finance", "HR", "IT"],
    required: false,
  },
  qualification: { label: "Qualification", type: "text", required: false },
  experience_years: {
    label: "Experience (Years)",
    type: "number",
    required: false,
  },
  joining_date: { label: "Joining Date", type: "date", required: false },
  address: { label: "Address", type: "textarea", required: false },
  reports_to: { label: "Reports To", type: "text", required: false },
  specialization: { label: "Specialization", type: "text", required: false },
  employee_id: { label: "Employee ID", type: "text", required: false },
  license_number: { label: "License Number", type: "text", required: false },
  consultation_hours: {
    label: "Consultation Hours",
    type: "text",
    required: false,
  },
  library_science_degree: {
    label: "Library Science Degree",
    type: "text",
    required: false,
  },
  shift_timing: {
    label: "Shift Timing",
    type: "select",
    options: ["Morning", "Evening", "Night", "Rotating"],
    required: false,
  },
  certification: { label: "Certification", type: "text", required: false },
  hr_certification: {
    label: "HR Certification",
    type: "text",
    required: false,
  },
  languages_known: {
    label: "Languages Known",
    type: "text",
    required: false,
  },
  lab_specialization: {
    label: "Lab Specialization",
    type: "select",
    options: ["Physics", "Chemistry", "Biology", "Computer", "General"],
    required: false,
  },
  lab_assigned: { label: "Lab Assigned", type: "text", required: false },
  driving_license: {
    label: "Driving License",
    type: "text",
    required: false,
  },
  license_expiry: { label: "License Expiry", type: "date", required: false },
  routes_managed: {
    label: "Routes Managed",
    type: "textarea",
    required: false,
  },
  company_name: { label: "Company Name", type: "text", required: false },
  gst_number: { label: "GST Number", type: "text", required: false },
  services_provided: {
    label: "Services Provided",
    type: "textarea",
    required: false,
  },
  contract_start: {
    label: "Contract Start Date",
    type: "date",
    required: false,
  },
  contract_end: { label: "Contract End Date", type: "date", required: false },
  purpose_of_visit: {
    label: "Purpose of Visit",
    type: "text",
    required: false,
  },
  visiting_department: {
    label: "Visiting Department",
    type: "text",
    required: false,
  },
  visit_date: { label: "Visit Date", type: "date", required: false },
  id_proof_type: {
    label: "ID Proof Type",
    type: "select",
    options: ["Aadhar", "PAN", "Passport", "Driving License"],
    required: false,
  },
  id_proof_number: {
    label: "ID Proof Number",
    type: "text",
    required: false,
  },
  occupation: { label: "Occupation", type: "text", required: false },
  student_name: { label: "Student Name", type: "text", required: false },
  student_class: { label: "Student Class", type: "text", required: false },
  relationship: {
    label: "Relationship",
    type: "select",
    options: ["Father", "Mother", "Guardian"],
    required: false,
  },
};
